# Generated by Django 3.0.2 on 2020-01-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupToken',
            field=models.CharField(max_length=32, verbose_name='token for inviting new users from that group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=10, verbose_name='name of a group (e.g. M3105)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='just a nickname of a user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passHash',
            field=models.CharField(max_length=128, verbose_name='hash for matching passwords'),
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expDate', models.DateTimeField(verbose_name='date and time of expiration of a deadline')),
                ('body', models.CharField(max_length=228, verbose_name='some text about this deadline')),
                ('state', models.BooleanField(verbose_name='0 - soft deadline, 1 - hard deadline')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homework.Group')),
            ],
        ),
    ]
