# Generated by Django 3.0.2 on 2020-01-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0005_auto_20200129_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='expDate',
            field=models.DateField(verbose_name='date of expiration of a deadline'),
        ),
    ]
